services:
  consumer-api-server:
    build: .
    image: consumer-api:v1
    container_name: consumer-api-server
    restart: always
    ports:
      - "8083:8083"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9094
    networks:
      - miw

networks:
  miw:
    external: true

#> docker compose up --build -d